// server/src/routes/stats.js

const express = require('express');
const router = express.Router();
const authMiddleware = require('./authMiddleware');
const ScriptHistory = require('../models/ScriptHistory');
const { listUserVideosFromS3 } = require('../s3Service');
const Video = require('../models/Video');

// Helper: parse date or return undefined
function parseDate(dateStr) {
  if (!dateStr) return undefined;
  const d = new Date(dateStr);
  return isNaN(d.getTime()) ? undefined : d;
}

// GET /api/stats/summary
router.get('/summary', authMiddleware, async (req, res) => {
  try {
    const { videoType = 'all', startDate, endDate } = req.query;
    const userId = req.user._id;
    const filter = { userId };

    // Date filtering
    const start = parseDate(startDate);
    const end = parseDate(endDate);
    if (start || end) {
      filter.createdAt = {};
      if (start) filter.createdAt.$gte = start;
      if (end) filter.createdAt.$lte = end;
    }

    // Count videos (scripts) generated by user
    const totalVideos = await ScriptHistory.countDocuments(filter);

    // For extensibility: add more aggregation if metadata contains stats
    // Count AI videos generated (from S3)
    let totalAIVideos = 0;
    try {
      const username = req.user && req.user.username ? req.user.username : '';
      const videos = await listUserVideosFromS3(userId, username);
      totalAIVideos = Array.isArray(videos) ? videos.length : 0;
    } catch (e) {
      totalAIVideos = 0;
    }

    // Count published videos for this user (publishedToYouTube true OR publishCount > 0)
    const publishedFilter = {
      owner: userId,
      $or: [
        { publishedToYouTube: true },
        { publishCount: { $gt: 0 } }
      ]
    };
    const publishedCount = await Video.countDocuments(publishedFilter);

    res.json({
      stats: [
        {
          title: "AI Videos Generated",
          value: totalAIVideos,
          change: "0%",
          changeType: "positive",
          comparison: "vs previous"
        },
        {
          title: "Scripts Generated",
          value: totalVideos,
          change: "0%",
          changeType: "positive",
          comparison: "vs previous"
        },
        {
          title: "Videos Published to YouTube",
          value: publishedCount,
          change: "0%",
          changeType: "positive",
          comparison: "vs previous"
        },
        {
          title: "Videos Published to Instagram",
          value: 0,
          change: "0%",
          changeType: "positive",
          comparison: "vs previous"
        }
      ]
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch summary stats.' });
  }
});

// GET /api/stats/timeseries
router.get('/timeseries', authMiddleware, async (req, res) => {
  try {
    const { videoType = 'all', startDate, endDate, interval = 'day' } = req.query;
    const userId = req.user._id;
    const match = { userId };

    // Date filtering
    const start = parseDate(startDate);
    const end = parseDate(endDate);
    if (start || end) {
      match.createdAt = {};
      if (start) match.createdAt.$gte = start;
      if (end) match.createdAt.$lte = end;
    }

    // Group by interval (only 'day' supported for now)
    const groupFormat = {
      $dateToString: { format: "%Y-%m-%d", date: "$createdAt" }
    };

    const data = await ScriptHistory.aggregate([
      { $match: match },
      {
        $group: {
          _id: groupFormat,
          count: { $sum: 1 }
        }
      },
      { $sort: { _id: 1 } }
    ]);

    // For timeseries, also get AI videos per day (from S3)
    // NOTE: S3 does not support timeseries queries; only ScriptHistory is shown in timeseries
    res.json({
      interval,
      data: data.map(d => ({
        date: d._id,
        totalScripts: d.count,
        totalAIVideos: null, // Not available per day from S3
        totalPublishedYouTube: null,
        totalPublishedInstagram: null
      }))
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch time-series stats.' });
  }
});

module.exports = router;